### ISSUE TITLE
Create a GitHub Action with `crate-ci/typos` to check for typos and open a pull request if found

### ISSUE THREAD

**Issue by tolgaozen** [melisacar/horse-project-using-python-folium#1]
## Objective

This issue outlines the steps to create a GitHub Action using `crate-ci/typos` with its GitHub Action support. The action will be manually triggered and, if any typos are found, it will open a pull request to fix them.

### 1. Set up the GitHub Action workflow

We will integrate `crate-ci/typos-action` into a workflow, allowing it to check for typos, write changes, and open a pull request.

Create a new file at `.github/workflows/typo-check.yml` with the following content:

```yaml
name: Check for typos

on:
  workflow_dispatch:  # Enables manual triggering
  push:
    branches:
      - main

jobs:
  typo_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run typo check
        uses: crate-ci/typos-action@v1
        with:
          files: '**/*.md'   # Example of file patterns to check (optional)
          isolated: false  # Set to true if you want to ignore implicit config files
          write_changes: true  # Writes changes to the local checkout

      - name: Commit and Push changes
        if: steps.typo_check.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b typo-fixes
          git commit -m "fix: automatically correct pre-commit issues"
          git push origin typo-fixes

      - name: Create Pull Request
        if: steps.typo_check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          branch: typo-fixes
          title: "Fix typos"
          body: "This PR fixes typos found by the typo-check workflow."
          commit-message: "fix: automatically correct pre-commit issues"
          labels: typo, automated
```

### 2. How it works

**Trigger:** The workflow can be manually triggered using workflow_dispatch or will automatically run when changes are pushed to the main branch.

**Typos check:** The action checks for typos in the specified files (e.g., **/*.md for markdown files).

**Writing changes:** If any typos are found and corrected (write_changes: true), the changes are committed and pushed to a new branch (typo-fixes).

**Pull request:** The peter-evans/create-pull-request action is used to open a pull request with the typo fixes.

### 4. Triggering the Action
To manually trigger the workflow:

1. Go to the Actions tab in your GitHub repository.
2. Select the Check for typos workflow.
3. Click Run workflow to manually trigger the typo check.
